### ISSUE TITLE
Header Problems concomitant with page numbering

### ISSUE THREAD

**Issue by fernandoroa** [davidgohel/officedown#105]
UPDATE: This description was not accurate because in a minimal example this problem does not appear in 0.3.0
The solution to the problem (add header and page number) is to add correctly the block_section at the end of the section, and add to it the page number field as in the last answer, to avoid using page number in the template

The recent version of officer allows to add a default header as in:

```
# In an .Rmd chunk
header_template <- function(txt) {
  block_list(
    fpar(ftext(txt),
        external_img(src = "image path", 
        width = 0.435, height = .175),
        fp_p = fp_par(
                      line_spacing = 2,
                      text.align = "left")
        )
  )
}

sec_pr <- prop_section(
  header_default = header_template("text")
)
block_section(sec_pr)
```

In this .Rmd yaml, calling a template that has page numbers in footer:
```
    reference_docx: template.docx
```
There are two effects depending on officedown 0.3.0 or 0.2.4
In 0.3.0 the header image gets displayed correctly, but no page number is observed
In 0.2.4 the header image does not get displayed, but the page number is displayed.

So, each version produces part of the desired result

**Comment by davidgohel** [comment]
hello, I just had a trial. I can see the page numbers after the inserted section in the default document provided in the package (doc here: https://github.com/davidgohel/officedown/blob/master/inst/rmarkdown/templates/word/skeleton/skeleton.Rmd)

<img width="1262" alt="Capture d’écran 2023-03-10 à 10 25 59" src="https://user-images.githubusercontent.com/4331618/224278161-cc5afea0-3d1c-48c4-a226-14669783b8a1.png">

Can you provide a reproducible example? I think you may have inserted a section but not the default one, just a new one (before the default one as it is defined at the end of the doc)

**Comment by fernandoroa** [comment]
thanks for the answer, Please confirm if you used the header code provided or similar.

**Comment by davidgohel** [comment]
I don't understand, sorry. I am asking if you can provide a reproducible example because I want to try to reproduce your issue. I can not confirm you anything until I am able to reproduce your issue :)

**Comment by fernandoroa** [comment]
Sorry, 
I think the problem was not correctly identified before; how to make the page numbers be in exactly the same pages of the header, 
this made the trick:

```
---
output:
  officedown::rdocx_document:
    reference_docx: template.docx
---
```{r, echo = FALSE}
library(officer)
library(officedown)
srcfile <- file.path(R.home("doc"), "html", "logo.jpg" )
header_template <- function(txt) {
  block_list(
    fpar(ftext(txt),
        external_img(src = srcfile, 
        width = 0.435, height = .175),
        fp_p = fp_par(
                      line_spacing = 2,
                      text.align = "left")
        )
  )
}

sec_pr <- prop_section(
  header_default = header_template("text"),
  type = "continuous"
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string1", "\n\n", sep = "")
```

```{r, echo = F}
block_section(prop_section(type = "continuous"))
```

```{r, echo = F}
block_section(sec_pr)
```

```{r, echo = F, results = "asis"}
knit_print_run(
    run_pagebreak()
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string2", "\n\n", sep = "")
```


```

**Comment by fernandoroa** [comment]
Related: https://stackoverflow.com/questions/75698221/how-to-get-header-and-page-number-in-a-docx-that-changes-orientation

**Comment by davidgohel** [comment]
I would use a template where header is containing the page number:

[template.docx](https://github.com/davidgohel/officedown/files/10943596/template.docx)

<img width="1196" alt="Capture d’écran 2023-03-10 à 16 46 40" src="https://user-images.githubusercontent.com/4331618/224360420-1e915a11-5380-4853-8711-109e8a825616.png">

`````
---
output:
  officedown::rdocx_document:
    reference_docx: template.docx
---
```{r, echo = FALSE}
library(officer)
library(officedown)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string1", "\n\n", sep = "")
```


```{r, echo = F, results = "asis"}
knit_print_run(
    run_pagebreak()
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string2", "\n\n", sep = "")
```

`````


<img width="1368" alt="Capture d’écran 2023-03-10 à 16 48 49" src="https://user-images.githubusercontent.com/4331618/224360922-b0442b14-8547-4771-a7e3-7fe619a2cc97.png">



If you need to add Word sections, you will have to define the header corresponding to each new section. It applies to previous content (until previous section).

<img width="1139" alt="Capture d’écran 2023-03-10 à 16 54 46" src="https://user-images.githubusercontent.com/4331618/224362456-8d06c60c-8e96-4029-9f55-8d2327084b23.png">
<img width="1184" alt="Capture d’écran 2023-03-10 à 16 54 51" src="https://user-images.githubusercontent.com/4331618/224362459-8362eca3-ab24-47c8-9d39-a484e4cd5ff6.png">

``````
---
output:
  officedown::rdocx_document:
    reference_docx: template.docx
---
```{r, echo = FALSE}
library(officer)
library(officedown)
srcfile <- file.path(R.home("doc"), "html", "logo.jpg" )
header_template <- function(txt) {
  block_list(
    fpar(ftext(txt),
        external_img(src = srcfile, 
        width = 0.435, height = .175),
        "this is page number ",
        run_word_field(field = "PAGE  \\* MERGEFORMAT"),
        fp_p = fp_par(
                      line_spacing = 2,
                      text.align = "left")
        )
  )
}

sec_pr <- prop_section(
  header_default = header_template("text"),
  type = "continuous"
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string1", "\n\n", sep = "")
```

```{r, echo = F}
block_section(sec_pr)
```

```{r, echo = F, results = "asis"}
knit_print_run(
    run_pagebreak()
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string2", "\n\n", sep = "")
```

``````


The last example shows the default section is used after a new section have been added. If you want to manage all headers, add a last section at then end so that it will be the last content defined in the doc and the default section will not have to appear:


``````
---
output:
  officedown::rdocx_document:
    reference_docx: template.docx
---
```{r, echo = FALSE}
library(officer)
library(officedown)
srcfile <- file.path(R.home("doc"), "html", "logo.jpg" )
header_template <- function(txt) {
  block_list(
    fpar(ftext(txt),
        external_img(src = srcfile, 
        width = 0.435, height = .175),
        "this is page number ",
        run_word_field(field = "PAGE  \\* MERGEFORMAT"),
        fp_p = fp_par(
                      line_spacing = 2,
                      text.align = "left")
        )
  )
}

sec_pr <- prop_section(
  header_default = header_template("text"),
  type = "continuous"
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string1", "\n\n", sep = "")
```

```{r, echo = F}
block_section(sec_pr)
```

```{r, echo = F, results = "asis"}
knit_print_run(
    run_pagebreak()
)
```

```{r results='asis', echo = F}
for(i in 1:50) cat("string2", "\n\n", sep = "")
```


```{r, echo = F}
block_section(sec_pr)
```

``````

<img width="1033" alt="Capture d’écran 2023-03-10 à 17 02 59" src="https://user-images.githubusercontent.com/4331618/224364329-7bd4cd06-946c-4af9-a07f-a3443ae6d082.png">

**Comment by davidgohel** [comment]
@fernandoroa why did you cross posted?

**Comment by fernandoroa** [comment]
Thanks for the answers, really helpful. Because after analysis it seems it is not a bug/issue, so I imagined stack was a more appropriate place to continue and you could close the non-bug.
