### ISSUE TITLE
captions, references and tables

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officedown#15]
Hi @dirkschumacher

As discussed last week, the following branch will contain improvements
https://github.com/davidgohel/officedown/tree/newfeatures

Some progress have been made and can be tested. An example is available here:
https://github.com/davidgohel/officedown/tree/newfeatures/inst/example

The expected result is the following file: 
[example.docx](https://github.com/davidgohel/officedown/files/4449743/example.docx)

I will go on this week and next week. Let me know if any question

**Comment by dirkschumacher** [comment]
Cool! Great work. I tested it and works fine in general so far.

What I noticed:
* when selecting a style that is not part of the reference docx, the error message says something like *Cound not find style "", ...* (it does not mention the style it could not find.
* Is it possible to have the reference to the table/figure also in the table/figure caption prefix? E.g. instead of Figure: <text>. Have Figure <figure ref>: <text>.
* I assume the other features (default list styles, table styles for body, header, specific cells (e.g. numeric)) are still work in progress, so I won't comment on them.

**Comment by davidgohel** [comment]
Hi, 

updates:

> when selecting a style that is not part of the reference docx[...]

fixed

> default list styles

This is now implemented. See example here: https://github.com/davidgohel/officedown/blob/newfeatures/inst/example/bookdown/_output.yml#L15 

Ordered list are defined with parameter `ol.style` and unordered lists are defined with parameter `ul.style`. 

I started the documentation, this is how it looks (I am only showing the list part here):

<img width="1030" alt="Capture d’écran 2020-04-20 à 11 39 16" src="https://user-images.githubusercontent.com/4331618/79737539-c31bc280-82fb-11ea-85bc-2fbe8fc97264.png">

> Is it possible to have the reference to the table/figure also in the table/figure caption prefix? E.g. instead of Figure: /text/. Have Figure /figure ref/: /text/.

I think that is already the case. I have updated the `reference_docx` so that we don't use a style with autonumbering in the same time than we autonumbered the captions.



I will start a the documentation so that users find it easier to find out what are the options.
