### ISSUE TITLE
Enable use of  <!---CHUNK_RUN_COLUMNBREAK--> as substitute to `r run_columnbreak`

### ISSUE THREAD

**Issue by Pindar777** [davidgohel/officedown#61]
I'm struggling with the multicolumn design inside an asis-r-chunk for generating automated reports.
Although I found in the [docs](https://davidgohel.github.io/officedown/articles/officer.html) that there is a "special comment"  nothing happens as opposed to using ` r run_columnbreak`.

In standard rmd this is fine, but I don't know how to invoke ` r run_columnbreak` in an "asis-chunk".

Hence, this has no effect:

```
  The following will be in a separated section with 2 columns:
  
  <!---BLOCK_MULTICOL_START--->
  
  Blah blah blah on column 1.
  
  <!---CHUNK_COLUMNBREAK--->
  Blah blah blah on column 2.
  
  <!---BLOCK_MULTICOL_STOP{widths: [3,3], space: 0.2, sep: true}--->
```

with
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] officedown_0.2.0 officer_0.3.14

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        cpp11_0.2.1       knitr_1.29        xml2_1.3.2
 [5] magrittr_1.5      uuid_0.1-4        R6_2.4.1          rlang_0.4.7
 [9] stringr_1.4.0     tools_4.0.2       xfun_0.18         rvg_0.2.5
[13] htmltools_0.5.0   systemfonts_0.3.1 yaml_2.2.1        digest_0.6.25
[17] bookdown_0.21     zip_2.1.1         memoise_1.1.0     evaluate_0.14
[21] rmarkdown_2.4     stringi_1.5.3     compiler_4.0.2    gdtools_0.2.2
[25] jsonlite_1.7.1
> rmarkdown::pandoc_version()
[1] '2.10.1'

**Comment by davidgohel** [comment]
Hello

This can not work as it is processed before knitting, but you are trying to generate this while knitting. 
Also `<!---CHUNK_COLUMNBREAK--->` has been dropped when the package has been submited to CRAN the first time. This is an error of mine, I should have deleted all references... Sorry. 


Would you consider working with `officer::block_list()`? I updated it so that it can handle tables, fpar and **sections**.

`````
---
date: "`r Sys.Date()`"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.cap = TRUE)
library(officedown)
library(officer)
library(officer)
fpt_blue_bold <- fp_text(color = "#006699", bold = TRUE)
fpt_red_italic <- fp_text(color = "#C32900", italic = TRUE)
value <- block_list(
  block_section(prop_section(type = "continuous")),
  fpar(ftext("hello world", fpt_blue_bold)),
  block_table(x = head(iris)),
  fpar(officer::run_columnbreak(), ftext("hello", fpt_blue_bold), " ",
       ftext("world", fpt_red_italic)),
  block_section(prop_section(
    section_columns = section_columns(widths = c(4,2.5), space = .25, sep = TRUE),
    type = "continuous"))
)
```


## Tables


```{r}
value
```


`````



<img width="1056" alt="Capture d’écran 2021-03-06 à 10 59 49" src="https://user-images.githubusercontent.com/4331618/110202756-14c53100-7e6b-11eb-8a03-e0a40ae0e680.png">



Your question was about using that in `asis-chunk`. So the next step implies you to work with pandoc...

````````

```{r result='asis'}
z <- paste("```{=openxml}", to_wml(value), "```", sep = "\n")
cat(z)
```
````````

Let me know if it answers your need :) I will soon complete some documentations about that here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#add-runs

**Comment by Pindar777** [comment]
@davidgohel Thank you for your detailed answer and the valuable hints!

At the moment I cannot use this approach, since the input of the columns is written inside a XLSX-file and makes use of markdown syntax like **BOLD**.  `block_table` and `fpar(ftext())` just pass the text. Is there a function that invokes a "translation"?

My current solution is to generate the whole rmd-text-file through a loop and export it. The title can be altered by the set_title parameter.

**Comment by davidgohel** [comment]
OK

> Is there a function that invokes a "translation"?

Not to my knowledge, the ftExtra package has this feature, but it only applies to flextable content.

**Comment by Pindar777** [comment]
@davidgohel I think this gonna work! I created some elaborated UDF with help of your flextable package. Hence, I only need to add the colformat_md() from frExtra. I check this out.

**Comment by Pindar777** [comment]
@davidgohel  o it turns out the colformat_md() does not support multiple paragraphs which is invoked by 
- TEXT...
Which is a pity because enumerations are important for the type of document I do want to "compile".
