### ISSUE TITLE
Missing Header and Footer from the docx template with the new version 0.2.2

### ISSUE THREAD

**Issue by tdemarchin** [davidgohel/officedown#68]
Hi, 
I noticed with the new version 0.2.2 that header and footer from the docx template are missing from the generated word. 
Everything works well with version 0.2.1.
I guess something is broken in the new version :-)

**Comment by davidgohel** [comment]
Please follow the guidelines, it really helps

Could you install the latest version on github, a fix has been done recently about a similar issue

**Comment by tdemarchin** [comment]
Hi David,

Yes sorry, I just tried with the Github version. 
Indeed, the header and footer appear again but there is an unwanted space in the left margin. It should be 1.27cm according to the template but it is more than that (although 1.27 is displayed in the dialog box of Word...?). Also, top and bottom margins are not the same as in the template. 
I can't find the similar issue you are mentioning. Let me know if this is already discussed in that thread.

Thanks, 
Thomas.

**Comment by davidgohel** [comment]
It's in #67

I will change the margins to some classic default values (I thought it was ok but apparently not).

Since https://github.com/davidgohel/officedown/blob/master/NEWS.md#new-feature, the values of the margins are defined in the header of your R Markdown document and those of the template will not have any effect. 

An option to use those of the template would be nice I guess...

**Comment by tdemarchin** [comment]
Yes indeed, it would be great to have an option to use the margins of the template.
I'd like to thank you for all your work, this package is awesome and greatly improve my daily work!
I wrote an article to share my experience: https://towardsdatascience.com/awesome-r-markdown-word-report-with-programmatically-inserted-headings-outputs-and-19ad0de29a22

**Comment by camitz** [comment]
Hello!

We noticed this issue as well. The latest fix attempt appears not to work. 

I can see what the fix is meant to do and it looks about based on an examination of the differences in the xml. But it's not there.

The diff also gives a clue about copying the margin settings, something we've also noticed. I'll post a new issue on this.

![image](https://user-images.githubusercontent.com/2123572/119152837-f544aa00-ba50-11eb-90ed-4cfb7f763f69.png)

I'm quite sure I've used the latest commit. I've tried using a local fork also.

Attaching my work. Let me know if I can assist.

[officedown issue 68 MC.zip](https://github.com/davidgohel/officedown/files/6523216/officedown.issue.68.MC.zip)

**Comment by davidgohel** [comment]
@camitz Here it does not work as expected because your image only belong to the first page section. 

Using the previous behavior will help a lot and I will see for this particular problem. 

It may be a long work as for now, officer and officedown does not manage yet these options (first page section, odd page, etc.) and I did not work on the subject yet.

**Comment by davidgohel** [comment]
See also #75

> It should be fixed now. You will need to update 'officer' with the dev version (where the problem was) and 'officedown' (recently updated). It should be on CRAN in two weeks.


```
remotes::install_github("davidgohel/officer")
remotes::install_github("davidgohel/officedown")
```


> You can see a simple 'R Markdown' example here: https://github.com/davidgohel/officedown/blob/483e5383993024ed542fc57407279a630441ee90/tests/testthat/rmd/sections.Rmd and the expected output here:  
![](https://github.com/davidgohel/officedown/raw/483e5383993024ed542fc57407279a630441ee90/tests/testthat/_snaps/rdocx-sections/docx-sections.png)
