### ISSUE TITLE
Import the figure as its original height/width ratio

### ISSUE THREAD

**Issue by xiaochi-liu** [davidgohel/officedown#83]
Hello, may I propose a feature request of importing a figure as its original height/width ratio?

For example, I have a well-designed figure as follows:

![image](https://user-images.githubusercontent.com/48895627/146634217-f5bed69b-6c09-4695-b167-554448b8b889.png)

If I use the following code to add this figure

```{r}
knitr::include_graphics("the file path to a figure")
```

in the Word document generated by `officedown`, the figure would look like this:

![image](https://user-images.githubusercontent.com/48895627/146634302-2fe2dfbc-55ea-4672-a5cd-26010ef4485d.png)

On [StackOverflow](https://stackoverflow.com/questions/70312388/how-to-import-a-figure-as-its-original-height-width-ratio), I have got a solution for this problem. That is:

``````
```{r}
library(imager)
my_pic <- load.image("xxx.png")
asp_rat <- dim(my_pic)[2]/dim(my_pic)[1] #find our aspect ratio

```

```{r fig.asp = asp_rat, fig.height = ??, fig.width = ??} #choose the best for your pic
knitr::include_graphics("xxx.png") 
```
``````

I was wondering, is there a more direct way to import the figure as its original height/width ratio? And how to maximize the figure size (i.e., make a figure's width occupy the whole length of the line)?

I love this package and am using it to draft my PhD thesis. Your kind guidance is much appreciated!

**Comment by xiaochi-liu** [comment]
Hello, may I get any help with this question? Thank you so much!

**Comment by davidgohel** [comment]
sure, 

Function `knitr::include_graphics()` is part of package 'knitr', not 'officedown'. I am afraid I can't do anything for modifying `include_graphics()`

**Comment by xiaochi-liu** [comment]
Thanks @davidgohel!

Got it. So is there any other way to keep the original height/width ratio when importing a figure?

I like the `officedown` package and I'm using it to draft the thesis, which contains a large amount of figures...

**Comment by davidgohel** [comment]
It is probably easy with only `magick::image_read()`. 

Why not using the classical way that works well? 

I just tried and without using `include_graphics()` but usual markdown, it works as expected:

``````
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
library(officer)
library(officedown)
```

![](zzz.png)

``````


<img width="1099" alt="Capture d’écran 2022-02-14 à 13 27 57" src="https://user-images.githubusercontent.com/4331618/153864342-f7754bc4-7a65-4b62-bc7b-4a23a246a0f6.png">

**Comment by davidgohel** [comment]
For future readers

`knitr::include_graphics` is not part of officedown but knitr. There is nothing to do with package officedown.

Users should use the Markdown syntax to insert images in a markdown document. (note : this does not apply only to officedown format but to all Markdown format), 


```
![caption](path/to/image)
```

**Comment by xiaochi-liu** [comment]
Thank you very much for your advice, @davidgohel.

The classical way of Markdown can insert the figure as its original height/width ratio. May I ask, can it be auto-numbered and cross-referenced?

I also tried `magick::image_read()`. This can be auto-numbered, but `officedown` still change the ratio:

``````
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
library(officer)
library(officedown)
library(magick)
```

![The result of MAE](figures/mae and test - update.png

```{r mae, fig.cap="MAE"}
mae <- image_read('figures/mae and test - update.png')
mae
```
``````

![image](https://user-images.githubusercontent.com/48895627/154404262-92944c5b-bd79-4282-b06e-07711507f6a3.png)

**Comment by davidgohel** [comment]
Captions are simple paragraphs.  Use markdown or use what is documented in the manual:

https://ardata-fr.github.io/officeverse/officedown-for-word.html#custom-cross-reference

**Comment by davidgohel** [comment]
@alapo why don't you use the markdown tag for image? It respects dimensions. 

The SO you linked is about changing graph dimensions so that it fills a page. Here the question is how to embed an external image in A word document. 

I think the answer is to simply use markdown tag for image.

**Comment by alapo** [comment]
@davidgohel  I am unsure. The document in the SO question is for a scientific publication...as far as I am aware if you use the markdown tag it would mean that you cannot reference the image in text. In order to convert from pixel information using `magick::image_info` you would need to specify the dpi/resolution. Apologies for the comment.

**Comment by xiaochi-liu** [comment]
Thanks for your advice @davidgohel.

Sometimes, making figures for publication can involve a large amount of code (computation), especially when mapping or setting complicated ashthetics. If we print them directly, the rendering of the document is time-consuming.

In addition, the `fig.height` and `fig.width` settings of the code chunk are not always working appropriately for the rendering output. That is, a suitable setting for the code chunk output may become unsuitable in the rendering Word document. This situation often happens when the figure is large or with multiple panels. I also encountered this problem when using `bookdown`.

Therefore, it might be easier to save the figure as a fixed PNG or JPEG then inserted it back.

**Comment by davidgohel** [comment]
OK, thanks for the explanation. I think I understand now. 

1. You don't want output graphics with *the classical way* (you should see caching options, it could help a lot), so you generated graphics in images. But these graphics need captions and should be *cross-referencable*.
2. In the same time, you want a similar rendering between the word output and what you are seeing in the R Markdown view (probably in RStudio), Word is a *paged* support and HTML (the R Markdown editor) has different behavior. 


# For 1:

``````
---
title: "test"
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(officedown)
library(officer)

z <- run_autonum(seq_id = "fig", pre_label = "Fig ",
                 tnd = 1, bkm = "")

```

# An example

```{r}
block_caption("blah",
  style = "Image Caption",
  autonum = set_autonum_bookmark(z, bkm = "fig1")
)
```

![hey hey](zz.png)

# Another example

```{r}
block_caption("blah blah",
  style = "Image Caption",
  autonum = set_autonum_bookmark(z, bkm = "fig2")
)
```

![ho ho](zz.png)

## Reference

This cross ref fig1 : \@ref(fig:fig1)

This cross ref fig1 : \@ref(fig:fig2)

``````

<img width="1545" alt="Capture d’écran 2022-02-24 à 09 24 35" src="https://user-images.githubusercontent.com/4331618/155486373-9a1b37a7-b7f9-47ab-8d09-1cb158405195.png">



# For 2:

Unless you can show a reproducible example, I think `fig.height` and `fig.width` are working as expected. If you want to declare an issue, you should always come with a reproducible example. R Markdown editor (visual or not) is not a WYSIWYG interface. 

You need to consider HTML and Word are 2 different formats. Word has a maximum width, this does not affect display in R Markdown viewer that is HTML. If your Word doc has a 7 inches' width, figures' width should not exceed that width because they won't be resized as in a Web browser. 

I think you are making the assumption that formats should all behave the same, but it's not the case. If you want an HTML 'paged' format, I highly recommend package pagedown. If you need to stick to Word format, you'll have to live with its characteristics.

**Comment by xiaochi-liu** [comment]
Got it. This works perfectly on my side. Thank you so much for your kind guidance, @davidgohel. I really appreciate that!
